version: '3'
services:

  sweb:
    build:
      context: ./sweb
      dockerfile: Dockerfile
    volumes:
      - ./sweb/www:/usr/share/nginx/html
    deploy:
      replicas: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sweb.rule=Host(`localhost`)"
        # Parametre pour HTTPS
      - "traefik.http.routers.sweb.tls=true"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`)"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
       # Stripper
      - "traefik.http.routers.api.middlewares=api-strip"
      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"
       # Sticky session
      - "traefik.http.services.api.loadBalancer.sticky.cookie=true"
      - "traefik.http.services.api.loadBalancer.sticky.cookie.name=api_sticky_cookie"
       # Parametre pour HTTPS
      - "traefik.http.routers.api.tls=true"

  reverse-proxy:
    image: traefik:v2.10
    command:
     - "--api.insecure=true"
     - "--providers.docker"
     - "--entrypoints.web.address=:80"
     - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
        # Parametre pour HTTPS
      - ./certificat:/etc/traefik/certificates
      - ./traefik.yml:/etc/traefik/traefik.yaml

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped